"""Constantes del módulo e-CF.

Incluye compatibilidad con constantes usadas por versiones previas del paquete.
"""

# Modos soportados
DIRECT_DGII = "DIRECT_DGII"
PSE_EXTERNAL = "PSE_EXTERNAL"
PSE_ECOSEA = "PSE_ECOSEA"

ECF_MODES = (DIRECT_DGII, PSE_EXTERNAL, PSE_ECOSEA)

# Estados de documento
ECF_STATUS_DRAFT = "DRAFT"
ECF_STATUS_SIGNED = "SIGNED"
ECF_STATUS_SENT = "SENT"
ECF_STATUS_PROCESSING = "PROCESSING"
ECF_STATUS_ACCEPTED = "ACCEPTED"
ECF_STATUS_CONDITIONAL = "CONDITIONAL"
ECF_STATUS_REJECTED = "REJECTED"
ECF_STATUS_ERROR = "ERROR"

ECF_STATUSES = (
    ECF_STATUS_DRAFT,
    ECF_STATUS_SIGNED,
    ECF_STATUS_SENT,
    ECF_STATUS_PROCESSING,
    ECF_STATUS_ACCEPTED,
    ECF_STATUS_CONDITIONAL,
    ECF_STATUS_REJECTED,
    ECF_STATUS_ERROR,
)

ECF_PENDING_CHECK_STATUSES = (ECF_STATUS_SENT, ECF_STATUS_PROCESSING)
ECF_FINAL_OK_STATUSES = (ECF_STATUS_ACCEPTED, ECF_STATUS_CONDITIONAL)

# Eventos de auditoría
ECF_EVENT_BUILD_XML = "BUILD_XML"
ECF_EVENT_SIGN = "SIGN"
ECF_EVENT_AUTH = "AUTH"
ECF_EVENT_SEND = "SEND"
ECF_EVENT_STATUS_CHECK = "STATUS_CHECK"
ECF_EVENT_PDF = "PDF"
ECF_EVENT_ERROR = "ERROR"

ECF_EVENT_TYPES = (
    ECF_EVENT_BUILD_XML,
    ECF_EVENT_SIGN,
    ECF_EVENT_AUTH,
    ECF_EVENT_SEND,
    ECF_EVENT_STATUS_CHECK,
    ECF_EVENT_PDF,
    ECF_EVENT_ERROR,
)

# Compatibilidad con implementación previa
EcfMode = {mode: mode for mode in ECF_MODES}
EcfFinalStatuses = set((ECF_STATUS_ACCEPTED, ECF_STATUS_CONDITIONAL, ECF_STATUS_REJECTED, ECF_STATUS_ERROR))
EcfPdfStatuses = set(ECF_FINAL_OK_STATUSES)
